name: automate
channels:
  - pytorch
  - pyg
  - fvcore
  - iopath
  - bottler
  - pytorch3d
  - conda-forge
  - defaults
  
dependencies:
  - python
  - cudatoolkit=10.2
  - pytorch=1.10
  - pyg=2.0.3
  - numpy
  - pandas
  - pytorch-lightning
  - tensorboard
  - pyarrow
  - requests
  - scipy
  - matplotlib
  - dotmap
  - meshplot
  - ipykernel
  - fvcore
  - iopath
  - pip
  - eigen
  - occt
  - cmake
  - pybind11
  - pip:
    - pyrender