name: automate
channels:
  - pytorch
  - pyg
  - defaults
  - conda-forge
  
dependencies:
  - python
  - cudatoolkit=10.2
  - pytorch=1.10
  - pyg=2.0.3
  - numpy
  - pandas
  - pytorch-lightning
  - tensorboard
  - pyarrow
  - requests
  - scipy
  - matplotlib
  - dotmap
  - meshplot
  - ipykernel
